### ISSUE TITLE
uninitialized constant FontAwesome::Rails::IconHelper

### ISSUE THREAD

**Issue by abrambailey** [SeniorMedia/redirector_ui#1]
This happened when I tried to add the engine. Are you missing a dependency?

**Comment by Apokly** [comment]
Hi @abrambailey,

Have you tried adding `include FontAwesome::Rails::IconHelper` to your application helper ? https://github.com/bokmann/font-awesome-rails/pull/152

**Comment by Apokly** [comment]
I just published a [fix](https://github.com/SeniorMedia/redirector_ui/commit/ad11b008758922ab652b54dc5fd77128ee339a63) and re-published gem on [Rubygems](https://rubygems.org/gems/redirector_ui).
